import math
# parameters
DEFAULT_LENGTH = 5
IS_PAGE = False
DEFAULLT_WINDOW_HEIGHT = 800
DEFAULLT_WINDOW_WIDTH = 1200
DEFAULT_MENU_WIDTH = 300
PANEL_VERTIVAL_MAX = 2
PANEL_HORIZONTAL_MAX = 4
EQUAL_PANEL_HEIGHT = math.floor(DEFAULLT_WINDOW_HEIGHT / (PANEL_VERTIVAL_MAX+1))
EQUAL_PANEL_WIDTH = math.floor((DEFAULLT_WINDOW_WIDTH) / (PANEL_HORIZONTAL_MAX+1))

DEFAULT_COMPOSITION_ALPHA = 0